### PR TITLE
Adds !hz command for the tappers who seem to constantly need it.

### PR DESCRIPTION
**Pull request by fractal161**

### CODE REVIEW

**Comment by alex-ong** [comment]
Oh my god its happend.
Can you also Draw a markdown diagram of the field?

**Comment by alex-ong** [comment]
Also an "averaged" input sequence. For example
Minimal Input Sequence: `x--x--x--x`

**Comment by fractal161** [comment]
seems doable. couple questions:

i decided to have them enter number of taps instead of column, so i'm thinking i just draw line pieces going to the left. would that work?

also is the averaged input sequence based off of minimum rate?

**Comment by alex-ong** [comment]
`is the averaged input sequence based off of minimum rate`
All the eff/min rates are different ways to measure hz, based on the same input sequence, aren't they?

Put an X on frame 0, an X on the last frame, then linearly space the x's in the remaining area.

e.g. You have n frames and x taps (n=10, x=4)
```python
frames = gravity * (19 - height) # 10)
taps = 4 # hardcode example)
min = (taps - 1) / ( frames- 1)
eff = taps / frames
```
```
Simulation (last frame only)
|..........| 
|..........| 
|..........| 
|.i........| 
|.i........| 
|.i........| 
|.i........| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
|xxxxxxxxxx| 
```
Sample input
`x--x--x--x `
Min rate: 15hz
Eff rate: 15hz ( i can't maths)

**Comment by fractal161** [comment]
I don't think they are (min/effective). I used Hydrant's formulas for min/effective, and the best interpretation i can find is that effective is like the worst possible frame delay before the first tap. I can show you diagrams if you want over discord.

**Comment by alex-ong** [comment]
Sure lets discuss there.

**Comment by professor-l** [comment]
This almost looks good - you have the majority of the function wrapped in an `else` block, though, and we've implemented `CommandException` for that exact reason.  If you change the "unrealistic inputs" message to a `CommandException` with the same string passed to it, you can get rid of the `else` and clean up the method a bit.

Also, would  you mind wrapping your sequence generating code in a helper method on the class?  It helps clean things up and keeps everything clear for parsing the source code later or moving things around.  Other than those to (very nitpicky) things, the code looks good.  Thanks!

**Comment by fractal161** [comment]
It's still possible for the upper bound of the hz range to be much greater than 30hz, but the lower bound is still less and I think people can use their best judgement.

**Comment by alex-ong** [comment]
> It's still possible for the upper bound of the hz range to be much greater than 30hz, but the lower bound is still less and I think people can use their best judgement.

That's fine; I think the "sample sequence" will enable them to make their own judgement.
image

**Comment by alex-ong** [comment]
Merging.

**Pull request merged**
